"""
Blank extraction A1 (Plate1) for each replicate and strain. 

Replicates:
  - KT, Salmonella, Serratia : 4 replicates
  - P1, P2, P3: 5 replicates
  - PA: 3 replicates
"""

import module_andalena as mym
import numpy as np
import matplotlib.pyplot as plt
import json
import os
import openpyxl
import pandas as pd
import re

# Run from the scripts/ directory regardless of where this is launched from,
# so the relative ../data paths resolve correctly.
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

plt.rcParams["font.family"] = "Arial"

# ===================
# BLANK EXTRACTION
# ===================

def get_blank_from_plate1(filepath):
  
    wb = openpyxl.load_workbook(filepath, data_only=True)
    ws = wb.active

    for row in ws.iter_rows():
        for cell in row:
            if cell.value == 'Abs':
                data_start_row = cell.row + 1
                data_start_col = cell.column + 1
                blank = ws.cell(row=data_start_row, column=data_start_col).value
                if isinstance(blank, str):
                    blank = float(blank.replace(',', '.'))
                return float(blank)

    raise ValueError(f"Not found: {filepath}")


# =============================================================================
# STRAINS + RESOURCES + REPLICATES
# =============================================================================

# Number of replicates per strain
n_replicates_per_strain = {
    'KT'        : 4,
    'Salmonella': 4,
    'Serratia'  : 4,
    'P1'        : 5,
    'P2'        : 5,
    'P3'        : 5,
    'PA'        : 3,
}

strains = list(n_replicates_per_strain.keys())

resources_1to8 = [
    'acetate', 'ascorbic acid', 'butyrate', 'citrate',
    'fructose', 'glucose', 'glycerol', 'starch'
]

# =============================================================================
# RESOURCE LANDSCAPE
# =============================================================================
with open('../data/d_plateWell_resourceCombinationBinary.json', 'r') as file:
    d_plateW_RCB = json.load(file)

with open('../data/d_resourceCombinationBinary_plateWell.json', 'r') as file:
    d_RCB_plateW = json.load(file)
# =============================================================================
# DICTIONARY
# =============================================================================

d_replicates_filename = {}

for st in strains:
    d_replicates_filename[st] = {}
    od_data_folder = '../data/0_raw_data/' + st + '_excel/'
    n_reps = n_replicates_per_strain[st]

    for r in range(1, n_reps + 1):
        rep_key = f'replicate{r}'
        d_replicates_filename[st][rep_key] = [
            od_data_folder + f'R{r}_Plate{plate}_{st}.xlsx'
            for plate in ['1', '2', '3']
        ]

# =============================================================================
# BLANK EXTRACTION
# =============================================================================

d_blank = {}

print("Extracting blanks automatically from well A1 of each Plate1...")
print("=" * 60)

for st in strains:
    d_blank[st] = {}
    print(f"\nStrain: {st}")
    for rep, files in d_replicates_filename[st].items():
        plate1_file = files[0]
        try:
            blank_value = get_blank_from_plate1(plate1_file)
            d_blank[st][rep] = blank_value
            print(f"  {rep}: {blank_value:.4f}  (from {os.path.basename(plate1_file)})")
        except FileNotFoundError:
            print(f"  ERROR: File not found {plate1_file}")
        except ValueError as e:
            print(f"  ERROR: {e}")

print("\n" + "=" * 60)
print("Blanks extracted successfully.\n")

# =============================================================================
# PROCESSING FUNCTION
# =============================================================================

def process_and_rename_replicates(csv_path, strain, n_replicates, output_folder):
    """
    Reads the generated CSV, removes specific columns and renames 
    replicate columns as R1, R2, R3, etc.
    
    Columns removed: Well, Resources, OD600 24h mean, OD600 24h std
    Columns renamed: OD600 24h repN → RN
    
    Args:
        csv_path: path to CSV generated by write_clean_data_to_csv
        strain: strain name
        n_replicates: number of replicates for that strain
        output_folder: folder where to save the processed CSV
    """
    try:
        # Read the CSV
        df = pd.read_csv(csv_path)
        
        print(f"  ℹ Original CSV dimensions: {df.shape[0]} rows × {df.shape[1]} columns")
        print(f"  ℹ Original columns: {list(df.columns)}")
        
        # Columns to drop
        cols_to_drop = ['Well', 'Resources', 'OD600 24h mean', 'OD600 24h std']
        cols_to_drop = [col for col in cols_to_drop if col in df.columns]
        
        if cols_to_drop:
            df = df.drop(columns=cols_to_drop)
            print(f"  ✓ Columns removed: {cols_to_drop}")
        
        # Rename replicate columns
        rename_dict = {}
        
        for col in df.columns:
            # Search for pattern "repN" where N is a number
            match = re.search(r'rep(\d+)', col, re.IGNORECASE)
            if match:
                rep_number = match.group(1)
                rename_dict[col] = f'R{rep_number}'
        
        if rename_dict:
            df = df.rename(columns=rename_dict)
            print(f"  ✓ Replicate columns renamed:")
            for old, new in rename_dict.items():
                print(f"      {old} → {new}")
        
        print(f"  ✓ Processed CSV dimensions: {df.shape[0]} rows × {df.shape[1]} columns")
        print(f"  ℹ Final columns: {list(df.columns)}")
        
        # Create output folder if it doesn't exist
        if not os.path.exists(output_folder):
            os.makedirs(output_folder)
        
        # Save the processed CSV
        output_filename = f'{strain}_L8_resources.csv'
        output_path = os.path.join(output_folder, output_filename)
        df.to_csv(output_path, index=False)
        
        print(f"  ✓ Processed CSV saved: {output_filename}")
        
        return True
        
    except Exception as e:
        print(f"  ✗ ERROR processing CSV for {strain}: {e}")
        import traceback
        traceback.print_exc()
        return False


# =============================================================================
# GENERATE AND PROCESS CSV 
# =============================================================================

for st in strains:
    print(f"\nProcessing strain: {st}")
    print("-" * 40)

    # --- Raw data ---
    d_raw_data = mym.add_raw_data_to_dic(d_replicates_filename[st])

    # --- Subtract blank (automatic per replicate) ---
    d_data = mym.get_processed_data(d_replicates_filename[st], d_blank[st])

    # --- Variance between replicates ---
    variance = mym.variance_between_replicates(d_data)

    # --- Variance plot ---
    fig = plt.figure()
    plt.plot(range(len(variance)), variance, 'ko')
    plt.ylabel('std of function')
    plt.xlabel('well')
    plt.title(st)
    plt.show()

    # # --- Create results folder if it doesn't exist ---
    # path_save_results = '../results/' + st
    # if not os.path.exists(path_save_results):
    #     os.makedirs(path_save_results)

    # # Uncomment to save figure:
    # # fig.savefig(path_save_results + '/variance.pdf', bbox_inches='tight')

    # # --- Compare replicate pairs at 24h ---
    # mym.compare_replicates(d_data, path_save_results)

    # --- Write clean data to temporary CSV ---
    save_folder_raw = '../data/1_csv_clean_data/'
    os.makedirs(save_folder_raw, exist_ok=True)
    file_name = st + '_landscape_8_resources.csv'
    mym.write_clean_data_to_csv(save_folder_raw, file_name, resources_1to8, d_data, d_plateW_RCB)

    # --- PROCESS AND RENAME REPLICATES ---
    csv_path = os.path.join(save_folder_raw, file_name)
    save_folder_processed = '../data/1_csv_clean_data/'
    n_reps = n_replicates_per_strain[st]
    
    process_and_rename_replicates(csv_path, st, n_reps, save_folder_processed)
    
    # Delete temporary CSV
    try:
        os.remove(csv_path)
    except:
        pass
    
    print('-----------------------------------')

print("\n" + "=" * 60)
print("✓ Processing completed for all strains.")
print("=" * 60)